### ISSUE TITLE
Improve chebyshev center computation

### ISSUE THREAD

**Issue by blegat** [JuliaPolyhedra/Polyhedra.jl#125]
Following an oral discussion with @ryalbert:

While the chebyshev radius is unique, the set of chebyshev center is only guaranteed to be a polyhedra of dimension at least one less than the dimension of the initial polyhedra.
Hence we should compute the polyhedral set of optimal solution and compute the chebyshev center of this set and continue like this recursively until the set of chebyshev center is of dimension 0, i.e. is one point.

**Comment by ferrolho** [comment]
Is this what you are trying to describe?

![IMG_20190705_121045](https://user-images.githubusercontent.com/4166093/60719045-642cbe80-9f1e-11e9-83f4-579149e1305d.jpg)
ABCD is a 2D rectangle whose set of Chebyshev centre is given by the line segment `st`.

I would assume, for most practical applications, computing the radius and one of the possible centres is sufficient. Perhaps this should be optional (if it gets implemented), because doing this recursively will have quite an impact on performance.

**Comment by blegat** [comment]
Yes, exactly. Having an option to design whether or not this is done seems best indeed.
