### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by blegat** [JuliaPolyhedra/Polyhedra.jl#40]
- [x] Move to JuliaDocs
- [ ] Add docstrings to all functionalities

**Comment by chriselrod** [comment]
Hi,
Not sure where the best place to add this is, but I figured it isn't totally off topic here, since this isn't clear to me from the documentation. Although perhaps it's just because I'm very unfamiliar with polyhedra and convex hulls.

What I want to do is find the convex hull of a set of points. It is straight forward and immediately obvious how to do so with SciPy from [their docs](https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.spatial.ConvexHull.html), even including an example plot.
I'll PyCall SciPy if I have to, but would rather use something here if anything can solve that problem.

For example, I can
```julia
using Sobol, Polyhedra, CDDLib

function sobmat(s::Sobol.SobolSeq{N}, n) where N
    out = Matrix{Float64}(N, n)
    buffer = Vector{Float64}(N)
    Sobol.skip!(s, n, buffer)
    for i ∈ 1:n
        next!(s, buffer)
        out[:, i] .= buffer
    end
    out
end

sm2d = sobmat(SobolSeq(2), 32);
v_rep = SimpleVRepresentation(sm2d');
p2d = polyhedron(v_rep, CDDLibrary());
```
???
No idea where to go from there, and the convexhull function doesn't seem to be what I'm looking for?

I also fixed some depwarnings for `ConvexHull.jl`, but couldn't figure out how to get the convex hull from there either. I also ran into the following issue on the master branch of `Polyhedra.jl` (similar error on the latest tagged version):
```julia
ERROR: MethodError: no method matching ConvexHull.ConvexHullPolyhedron{2,Float64}(::Polyhedra.PointIterator{2,Float64,2,Float64}, ::Polyhedra.RayIterator{2,Float64,2,Float64})
Stacktrace:
 [1] vconvert(::Type{ConvexHull.ConvexHullPolyhedron{2,Float64}}, ::Polyhedra.SimpleVRepresentation{2,Float64}) at /home/chris/.julia/v0.6/Polyhedra/src/representation.jl:252
 [2] ConvexHull.ConvexHullPolyhedron{2,Float64}(::Polyhedra.SimpleVRepresentation{2,Float64}) at ./sysimg.jl:77
 [3] polyhedron(::Polyhedra.SimpleVRepresentation{2,Float64}, ::ConvexHull.ConvexHullLib) at /home/chris/.julia/v0.6/ConvexHull/src/polyhedron.jl:110
```
I'd submit a pull request with my changes if anyone is interested. (I also started with a clone of saschatimme's fork, so credit to him).


My application is d-dimensional Delaunay triangulation.

**Comment by mforets** [comment]
To build the explicit convex hull of a set of *points in the plane* (not polyhedra), I recently coded an algorithm, in part because QuickHull.jl and CHull2d.jl were currently having build errors. This is in the [LazySets.jl](https://juliareach.github.io/LazySets.jl/latest/lib/operations.html#LazySets.convex_hull) project, and it has no relation with Polyhedra.jl however (maybe in the future?). You can see an example and how to plot it.

I tried the following with `Polyhedra` (to me there are no build errors even after `Pkg.checkout("Polyhedra")`, did you do that?):

```julia
julia> using Polyhedra, CDDLib
julia> P1 = polyhedron(SimpleVRepresentation(randn(15, 2)), CDDLibrary());
julia> P2 = polyhedron(SimpleVRepresentation(randn(15, 2)), CDDLibrary());
julia> convexhull(P1, P2)
...
begin
 30 3 real
...
```
it contains 30 points, but i expected that the final result contains less vertices 🤔

**Comment by chriselrod** [comment]
Sorry I wasn't clear, `CDDLib` worked for me, but I don't know how to go any further once I have the Polyhedra object:
```julia
julia> p2d = polyhedron(v_rep, CDDLibrary())
CDDLib.CDDPolyhedron{2,Float64}(Nullable{CDDLib.CDDInequalityMatrix{2,Float64,S} where S<:Union{CDDLib.GMPRational, Float64}}(), Nullable{CDDLib.CDDGeneratorMatrix{2,Float64,S} where S<:Union{CDDLib.GMPRational, Float64}}(V-representation
begin
 32 3 real
 1.0 0.546875 0.765625
snip to save space
 1.0 0.0234375 0.3984375
end), Nullable{CDDLib.CDDPolyhedra{2,Float64,S} where S}(), false, false, false, false)
```
Most of its (nullable) fields are empty, and from experimenting none of the functions in the docs seem to be what I'm looking for.
I could also just create matrices of half the number of points I want twice, and then add them together with convex hull. Which seems silly, and then I still don't know how to go from there -- all I seem to have done is get an object that `vcat`ed the two matrices.
Still don't know how to get the vertices...


LazySets looks cool, but I want something that would work for larger numbers (eg >8) dimensions. Was trying to figure things out with a smaller number first.

I'll also consider `Cxx` + [CGAL](https://doc.cgal.org/latest/Triangulation/index.html#Chapter_Triangulations).
I want to test an algorithm that needs multivariate Hermite interpolation of scattered "data".
Triangulation can help get there, but I may try more simply solving using radial basis functions first and exploring (more sophisticated) possible improvements later.

**Comment by blegat** [comment]
Thanks for the improvement suggestion to the doc ! We should make it clearer how to compute a convex hull indeed.
Once you have your polyhedron `p2d`, it already represents the convex hull.
If is is 2D, you can it with `using Plots; plot(p2d)` and it will show you the convex hull of the points.
If I understand correctly, you want to get the extreme points of the convex hull.
To do this, you need to do `removevredundancy!(p2d)`. Then the polyhedron will discard any point that is not extremal in its internal representation.

**Comment by blegat** [comment]
I have added a section about redundancy removal [here](https://juliapolyhedra.github.io/Polyhedra.jl/latest/utilities.html#Redundancy-1). What do you think of it ? Would have it helped or would you put it differently ?

**Comment by chriselrod** [comment]
I'm not the greatest at explaining myself -- what I was looking for was the edges connecting the vertices to form the convex hull.
The idea (taken from Wikipedia & elsewhere) was to add an extra dimension to the data ( = squared norm of old dimensions, so we get a parabola shape ), find the simplexes (hyper-triangles) of the convex hull, and then truncate off the added dimension so that the original space is now cut up into simplexes.

It's easy to visualize the process in 1 dimension; a 1 dimensional simplex is just a line segment.
You have a bunch of points on a number line, then add a second dimension ( = square of the first), so now you have a 2d parabola. You find the convex hull and the associated edges.
Truncate the added dimension, and you're left with a bunch of non-overlapping line segments: space has been divided up into 1d simplexes.

In two dimensions, the space would be cut up into triangles.
3d -> tetrahedrons, etc.

Basically, it's a way to divide an N dimensional space up into a bunch of N-dimensional triangles.

So in my actual application, none of the points are going to be in the interior, and none will be dropped. The purpose is to find all the simplexes.

But step 1 in figuring out how I could do things was just playing with the software and try to see if I could get what was going on.
SciPy was cool, because it showed a plot to see what it was doing, and the code also involved hull.simplices, so it was easy to see how to extract the simplexes from the hull object to make the plot (simplexes being, with two vertices, just a line segment extending between them). These are then straightforward to use in whatever other algorithms we may have.

Looking at the code for the [plot recipe](https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/master/src/recipe.jl), I see how it too gets the edges (1d simplex) for two dimensions.
But that algorithm doesn't generalize as is, and the fact the algorithm is wrapped up in the plots function seems to imply that what I'm looking for isn't currently supported.

Anyway, thank you for your time! I know it can be discouraging to put a lot of effort into a great open source project and have people just come in and complain about stuff, etc.
Right now I'm just exploring possibilities (that in the near term may not involve triangulation at all), so this isn't urgent. If I look at this more seriously in the next few days, I'll start looking into CGAL which offers to do the triangulation directly.

**Comment by mforets** [comment]
> Basically, it's a way to divide an N dimensional space up into a bunch of N-dimensional triangles.

@chriselrod : For low dims check the [JuliaGeometry](https://github.com/JuliaGeometry) ecosystem, eg. [Meshes.jl](https://github.com/JuliaGeometry/Meshes.jl). For n-dim, maybe [CGoGN_2](https://github.com/cgogn/CGoGN_2).

> I have added a section about redundancy removal here. What do you think of it ? Would have it helped or would you put it differently ?

@blegat : yes, i find it helpful like that in the docs, thanks. on the other hand, i noticed that this operation is too costly for a convex hull (should be in the order of the ms) for this example:

```julia
julia> P1 = polyhedron(SimpleVRepresentation(randn(1000, 2)), CDDLibrary());
julia> @time removevredundancy!(P1);
  0.222418 seconds (11 allocations: 304 bytes)
```
any idea why it's taking that much?

**Comment by blegat** [comment]
@chriselrod It seems to me that there is three sides to your questions:
* Is this functionality implemented by one of the library : Yes, by `QHull.jl`.
* Is the retrieval of the simplices part of the Polyhedra API : Not yet but I would consider a PR that add it.
* Is this functionality going to be implemented in Polyhedra so that any library has it : It depends on whether it is easy to implement on top of the existing API. If it is, I am ok to add it.

@mforets In 2 dimensions, you can do things very fast but CDD implements generic N-dimensional algorithms which are of course slower in 2D. I have checked with ProfileView, all the time is taken in the CDDLibrary. Also `canonicalize!` and `redundancyremove!` take about the same time so the time does not seem to be taken in linearity detection.
```julia
julia> P1 = polyhedron(SimpleVRepresentation(randn(1000, 2)), CDDLibrary());
julia> @time CDDLib.redundancyremove!(get(P1.ext))
  0.175308 seconds (69 allocations: 2.484 KiB)
julia> P1 = polyhedron(SimpleVRepresentation(randn(1000, 2)), CDDLibrary());
julia> @time CDDLib.redundancyremove!(get(P1.ext))
  0.220589 seconds (69 allocations: 2.484 KiB)
julia> P1 = polyhedron(SimpleVRepresentation(randn(1000, 2)), CDDLibrary());
julia> @time CDDLib.canonicalize!(get(P1.ext))
  0.176457 seconds (10 allocations: 272 bytes)
julia> P1 = polyhedron(SimpleVRepresentation(randn(1000, 2)), CDDLibrary());
julia> @time CDDLib.canonicalize!(get(P1.ext))
  0.206322 seconds (10 allocations: 272 bytes)
```
