### ISSUE TITLE
Concrete types

### ISSUE THREAD

**Issue by blegat** [JuliaPolyhedra/Polyhedra.jl#42]
Currently the fields of `Ray, Line, HalfSpace, ...` are `Union{GeometryTypes.Vec{N, T}, AbstractArray{T}}`, it would be more efficient, if the type of this array was included in the type, e.g.
```julia
struct HalfSpace{N,T,AT<:AbstractArray{T}}
    a::AT
    β::T
end
```
or we could do
```julia
struct HalfSpace{N,T}
    a::StaticArrays.SVector{N, T}
    β::T
end
```
The first solution would allow us to benchmark different solutions and the advantage of the second solution is that it would automatically convert the array to the more efficient type. It would maybe do unnecessary conversion when using CDD, ... though
@rdeits @tkoolen What do you think ?

**Comment by tkoolen** [comment]
I've been going back and forth on this subject myself in RigidBodyDynamics, and honestly I've been a little inconsistent exactly because I can't make up my mind: for some types I've chosen the `SVector` solution, and for some the `<:AbstractVector` solution.

Parameterizing `HalfSpace` on the array type is certainly more flexible. I could imagine it being nice to have a mutable `HalfSpace` type, especially if you have lots of dimensions. Also, if you want to use this in combination with `ReverseDiff` then the array types need to be mutable (although that's arguably a design flaw in `ReverseDiff`).

However, parameterizing `HalfSpace` on the array type can 'silently' lead to lots of allocations. Suppose that through type promotion a regular `Vector` gets constructed somewhere in an algorithm, perhaps through interaction with a user input type that wasn't quite what you expected during the design or because of a careless refactor. If a `HalfSpace` is constructed based on the `Vector` (while you were implicitly assuming that it would be an `SVector`), then from that point on the algorithm will run fine, but everything will allocate lots of memory. So if you go with this approach, I would recommend setting up a bunch of benchmarks with `BenchmarkTools` that you can run as you make changes, to keep track of allocations for the main algorithms.

**Comment by blegat** [comment]
@tkoolen Thanks a lot for sharing your experience. I haven't made up my mind yet but currently I am leaning towards trying to remain flexible in the interface. For double description/projection algorithm we usually thing of it as low-dimensional because it is so heavy computationally but the redundancy removal part can be used by data with much higher dimension since it can be solved by an LP so it might makes sense to use `Vector` for this kind or applications.

**Comment by rdeits** [comment]
Another thing to consider: Currently all of the Polyhedra.jl types have the dimension of the polyhedron/half space/etc. as part of the type. That means that, for example, the following code is type-unstable:

```
SimpleHRepresentation(eye(3), ones(3))
```

because the compiler doesn't know that the return type will be a `SimpleHRepresentation{3, Float64}` (`@code_warntype` shows `Polyhedra.SimpleHRepresentation{_,Float64} where _`). 

If, instead, we had a definition like:

```
struct SimpleHRepresentation{T, A <: AbstractMatrix{T}, V <: AbstractVector{T}}
  A::A
  b::V
end
```

then that constructor could be type-stable, and a user could also call the constructor with `StaticArray` arguments and get a statically-dimensioned polyhedron. 

I wonder if by doing this we could basically just let the underlying array do all the hard work for us.

**Comment by blegat** [comment]
Yes that is a good point. One blocking issue is that we need to have N as
an argument to inherit from GeometryTypes.AbstractGeometry. We might
consider a different approach for that. We could create a new type
inheriting AbstractGeometry and containing the polyhedron as a field.
We could even move the plotting code to another package PolyhedraPlot.jl
and remove the GeometryTypes and PlotRecipe dependencies.
What do you think ?

**Comment by rdeits** [comment]
Oh, right, good point. Hm, I'm not sure how to handle that, especially the AbstractGeometry inheritance.  In particular, if we allow polyhedra that don't contain their dimension in the type parameters, then something like `decompose()` would become type-unstable.

**Comment by goretkin** [comment]
In case it's not known, `GeometryTypes` has `AbstractFlexibileGeometry`, the intent of which I think is to not have the dimensionality as a type parameter.
https://github.com/JuliaGeometry/GeometryTypes.jl/blob/3cf662d4819598d65355708481dcf2834f785541/src/types.jl#L180

**Comment by blegat** [comment]
@rdeits The full dimension has been removed in https://github.com/JuliaPolyhedra/Polyhedra.jl/pull/116. To use the polyhedron `p` with GeometryTypes for 3D plotting, you now need to do `PolyhedronGeometry(p)`
