### ISSUE TITLE
create polyhedron from iterable of `HalfSpace`s

### ISSUE THREAD

**Issue by goretkin** [JuliaPolyhedra/Polyhedra.jl#57]
I see constructors for constructing `Polyhedron` from `HRepIterator`, but I don't see any methods for constructing from, say, `collect(hreps(some_poly)`.

I'm also missing methods for constructing an HRepIterator from an iterable of `HRepElement`.

Is there a recommended way besides constructing the `HRepresentation` `A` matrix directly?

I'm asking because I notice that there is `SimpleHRepresentation` and `LiftedHRepresentation`, which use a different matrix representation. So intersect a halfspace with both possible representations, I'm using `intersect`, which isn't defined on `Polyhedron` and `HalfSpace`:

```julia
p_w_l_hrep = polyhedron(SimpleVRepresentation(rand(4,2)))
p_w_s_hrep = polyhedron(SimpleHRepresentation(rand(4,2), rand(4)))

julia> typeof(hrep(p_w_s_hrep))
Polyhedra.SimpleHRepresentation{2,Float64}

julia> typeof(hrep(p_w_l_hrep))
Polyhedra.LiftedHRepresentation{2,Float64}


hs = HalfSpace(rand(2),rand())
halfspace_singleton = SimpleHRepresentation(reshape(hs.a, length(hs.a), 1)', [hs.β])

intersect(hrep(p_w_l(or_s)_hrep), hsap)
```

Thanks for this library!

**Comment by goretkin** [comment]
And this is more of a general question, but what does `Lifted` mean here?

**Comment by blegat** [comment]
> Is there a recommended way besides constructing the HRepresentation A matrix directly?

No but that is going to change with https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/41

> which isn't defined on Polyhedron and HalfSpace

It is [here](https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/5d8addf9d8566330343165414bf1a4a4b2587fd8/src/repelemop.jl#L155), it is missing from the doc though.

> And this is more of a general question, but what does Lifted mean here?

Given a polynomial of degree at most `d`, you can homogenize it by replacing `x` by `x' / z` where `z = 1`. See [here](https://en.wikipedia.org/wiki/Homogeneous_polynomial#Homogenization).
You then have a polynomial in `x'` with all monomials of degree `d`.
This approach is used by CDD and LRS. When you drop the constraint `z = 1` you end up with only homogeneous halfspaces (the constant is zero) in `(x, z)`) hence you have a polyhedral cone so instead of searching for rays and points you can just search for rays. Also, if you have points and rays and you are looking for the facets, you replace a point `x` by `(1, x)` and a ray `r` by `(0, r)` and you say that they are all rays in dimension `n+1`. Then you consider that these are in face homogeneous halfspace (duality correspondance) and you are looking for rays.
That allows them to handle all cases just with an algorithm for enumerating rays of a polyhedral cone.
It is called Lifted because you lift the space by adding one variable `z`.

**Comment by goretkin** [comment]
> It is here, it is missing from the doc though.

Oh, great. I saw that, but didn't realize `Polyhedron` would dispatch to that.

Thanks for the explanation.
