### ISSUE TITLE
matrix constructor for MatVRep doesn't exist, how to get element iterators

### ISSUE THREAD

**Issue by goretkin** [JuliaPolyhedra/Polyhedra.jl#76]
I'm trying to update to the latest Polyhedra and have a few questions. I'm fine with these changes, just trying to make sure I understand how to use the new interface.

I see `SimpleVRepresentation` was renamed to `MixedMatVRep`. Previously there was a constructor 
`SimpleVRepresentation(V::AbstractMatrix{T}, linset::IntSet=IntSet()) where {T <: Real} = SimpleVRepresentation{size(V, 2),T}(V, similar(V, 0, size(V, 2)), linset, IntSet())` which now looks to exist as `vrep` here: https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/31ecc3bce4958ee4c8d4000579162eab4186faaa/src/matrep.jl#L77 Is that intentional? (There is an analogous change for `SimpleHRepresentation` and `hrep`.)

Another change I wasn't able to fix is calls to `hreps` and `vreps` to construct an interator. I see there's now a `RepIterator` that is parametereized on `ElemT` (Element Type). I see also there's an unexported `vreps` and `hreps`, which seem to return a tuple of iterators including `SymPoint`, `Point`, `HyperPlane` and `HalfSpace`. Are users supposed to keep using these `hreps` and `vreps`, or do you prefer an alternative?

Thanks for your work on this library!

**Comment by blegat** [comment]
Thank you for your feedback ! I want the transition to be as smooth as possible so if we can make the warnings clearer, I am interested :)

The MixedMatRep constructors now no longer have default values for the arguments as they should be replaced in most cases with `vrep` and `hrep`. The warning is probably not well written there.

It is a bit unfortunate that I had to reuse the name `hreps` and `vreps` since I couldn't deprecate them. `hreps` and `vreps` are now functions used internally to return all the iterators but this is for more advanced usage I'd say which is why it is not exported. The user is expected to use `hyperplanes`, `halfspaces`, `points`, `lines` and `rays` to iterate through the elements. The `hreps` and `vreps` that were used previously are not type-stable so they have been discarded :)

**Comment by blegat** [comment]
Fixed by #79
